### ISSUE TITLE
Not redirecting to warning page

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/wp-bouncer#4]
When the logging limit amount is reached the user is logged out on the previous device but not redirected to login-warning.php. This also applies when using the filter `wp_bouncer_redirect_url`.

To recreate issue

1. Install latest version of WordPress.
2. Install WP Bouncer plugin
3. In a customization plugin add recipe as outlined [here](https://www.paidmembershipspro.com/allow-a-specific-number-of-active-sessions-with-a-single-user-account-useful-for-corporate-education-or-group-type-memberships/)
4. Set limit in this recipe to 1
5. Create new user account with subscriber role in WP
6. Login in to test site from two different browsers.

**Comment by ideadude** [comment]
Working on the redirect issue. It's pretty subtle. Would be fun for a little dive into WP codebase.

We hook into init like this:
add_action( 'init', array( $this, 'login_flag' ) );
The login_flag function has a param $redirect = true. Should default to true.
But init is sending an empty string as param1 to that.
Even though the init hook is coded like this: https://github.com/WordPress/WordPress/blob/d8586560237d49984bbb0235ce91ec4a320da1b2/wp-settings.php#L520

Seems that WP hooks send empty strings by default to the params if not specified. Not sure how/why/when this started happening.

Changing our hook code to specifically send 0 params lets our $redirect param default to true again:
add_action( 'init', array( $this, 'login_flag' ), 10, 0 );

Fixed in this commit: https://github.com/strangerstudios/wp-bouncer/commit/3fc7359ac42b1b1282e69167c425564799b3e120
